# Generated by Django 4.2.4 on 2023-09-02 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('족발,보쌈', '족발,보쌈'), ('찜,탕,찌개', '찜,탕,찌개'), ('돈까스,회,일식', '돈까스,회,일식'), ('피자', '피자'), ('고기구이', '고기구이'), ('양식', '양식'), ('치킨', '치킨'), ('중식', '중식'), ('아시안', '아시안'), ('백반,죽,국수', '백반,죽,국수'), ('도시락', '도시락'), ('분식', '분식'), ('카페,디저트', '카페,디저트'), ('페스트푸드', '페스트푸드')], default='치킨', max_length=30, verbose_name='카테고리종류')),
                ('content', models.TextField()),
                ('address', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_compelete', models.BooleanField(default=False)),
                ('target_number', models.IntegerField(default=1, help_text='최대 10명만 가능합니다.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='목표인원')),
                ('join_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
