# Generated by Django 4.2.4 on 2023-09-05 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recruited_users',
        ),
    ]
