# Generated by Django 4.2.4 on 2023-08-18 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatRoom',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('chatroom', models.ForeignKey(db_column='chatroom_id', on_delete=django.db.models.deletion.CASCADE, related_name='roomJoin', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chatRoomJoin',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chatroom', models.ForeignKey(db_column='chatroom_id', on_delete=django.db.models.deletion.CASCADE, related_name='chatRoom', to='chat.chatroom')),
            ],
            options={
                'db_table': 'chatMessage',
            },
        ),
    ]
