# Generated by Django 4.2.4 on 2023-09-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomjoin',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
