# Generated by Django 4.2.4 on 2023-08-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_user_alter_chatroom_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroomjoin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
