# Generated by Django 4.2.4 on 2023-08-25 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatroomjoin_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='blacklist',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, null=True, size=None),
        ),
    ]
