# Generated by Django 4.2.4 on 2023-08-29 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatroom_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroomjoin',
            name='chatroom',
            field=models.ForeignKey(db_column='chatroom_id', on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
    ]
