# Generated by Django 4.2.4 on 2023-08-29 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('chat', '0007_alter_chatroomjoin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='post',
            field=models.OneToOneField(db_column='post_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
