# Generated by Django 4.2.4 on 2023-08-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatroomjoin_chatroom_alter_chatroomjoin_user'),
        ('chat', '0008_chatroom_post'),
    ]

    operations = [
    ]
