# Generated by Django 4.2.4 on 2023-09-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_merge_20230901_1030'),
        ('chat', '0010_remove_chatmessage_updated_at_and_more'),
    ]

    operations = [
    ]
