# Generated by Django 4.2.4 on 2023-08-21 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updatd_at',
        ),
        migrations.AddField(
            model_name='post',
            name='is_compelete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='join_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.IntegerField(default=0, help_text='최대 10명만 가능합니다.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='목표인원'))], verbose_name=''),
        ),
        migrations.AddField(
            model_name='post',
            name='target_number',
            field=models.IntegerField(default=0, help_text='최대 10명만 가능합니다.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='목표인원'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('족발,보쌈', '족발,보쌈'), ('찜,탕,찌개', '찜,탕,찌개'), ('돈까스 회 일식', '돈까스 회 일식'), ('피자', '피자'), ('고기구이', '고기구이'), ('양식', '양식'), ('치킨', '치킨'), ('중식', '중식'), ('아시안', '아시안'), ('백반,죽,국수', '백반,죽,국수'), ('도시락', '도시락'), ('분식', '분식'), ('카페,디저트', '카페,디저트'), ('페스트푸드', '페스트푸드')], default='치킨', max_length=30, verbose_name='카테고리종류'),
        ),
    ]
