# Generated by Django 4.2.4 on 2023-09-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
