# Generated by Django 4.2.4 on 2023-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_recruited_users_alter_post_join_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('족발,보쌈', '족발,보쌈'), ('찜,탕,찌개', '찜,탕,찌개'), ('돈까스,회,일식', '돈까스,회,일식'), ('피자', '피자'), ('고기구이', '고기구이'), ('양식', '양식'), ('치킨', '치킨'), ('중식', '중식'), ('아시안', '아시안'), ('백반,죽,국수', '백반,죽,국수'), ('도시락', '도시락'), ('분식', '분식'), ('카페,디저트', '카페,디저트'), ('페스트푸드', '페스트푸드')], default='치킨', max_length=30, verbose_name='카테고리종류'),
        ),
    ]
